
# hugo server --minify --themesDir ../.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/

# baseURL = 'https://example.com/'
baseURL = 'https://hardflaccidhub.com/'

title = 'Hard Flaccid Hub'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
# enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  languageCode = 'en-US'
  weight = 1

[languages.fr]
  contentDir = 'content.fr'
  languageName = 'Français'
  weight = 2

[languages.es]
  contentDir = 'content.es'
  languageName = 'Español'
  languageCode = 'es-ES'
  weight = 3

[languages.pt]
  contentDir = 'content.pt'
  languageName = 'Português'
  languageCode = 'pt-PT'
  weight = 4

[languages.it]
  contentDir = 'content.it'
  languageName = 'Italiano'
  languageCode = 'it-IT'
  weight = 5

[languages.ro]
  contentDir = 'content.ro'
  languageName = 'Limba Română'
  languageCode = 'ro-RO'
  weight = 5.5

[languages.de]
  contentDir = 'content.de'
  languageName = 'Deutsch'
  languageCode = 'de-DE'
  weight = 6

[languages.nl]
  contentDir = 'content.nl'
  languageName = 'Nederlands'
  languageCode = 'nl-NL'
  weight = 7

[languages.da]
  contentDir = 'content.da'
  languageName = 'Dansk'
  languageCode = 'da-DK'
  weight = 8

[languages.nb]
  contentDir = 'content.nb'
  languageName = 'Norsk'
  languageCode = 'nb-NO'
  weight = 9

[languages.sv]
  contentDir = 'content.sv'
  languageName = 'Svenska'
  languageCode = 'sv-SE'
  weight = 10

[languages.fi]
  contentDir = 'content.fi'
  languageName = 'Suomi'
  languageCode = 'fi-FI'
  weight = 11

[languages.et]
  contentDir = 'content.et'
  languageName = 'Eesti keel'
  languageCode = 'et-EE'
  weight = 12

[languages.hu]
  contentDir = 'content.hu'
  languageName = 'Magyar'
  languageCode = 'hu-HU'
  weight = 13

[languages.lv]
  contentDir = 'content.lv'
  languageName = 'Latviešu valoda'
  languageCode = 'lv-LV'
  weight = 14

[languages.lt]
  contentDir = 'content.lt'
  languageName = 'Lietuvių kalba'
  languageCode = 'lt-LT'
  weight = 15

[languages.pl]
  contentDir = 'content.pl'
  languageName = 'Polski'
  languageCode = 'pl-PL'
  weight = 16

[languages.cs]
  contentDir = 'content.cs'
  languageName = 'Čeština'
  languageCode = 'cs-CZ'
  weight = 17

[languages.sk]
  contentDir = 'content.sk'
  languageName = 'Slovenčina'
  languageCode = 'sk-SK'
  weight = 18

[languages.ru]
  contentDir = 'content.ru'
  languageName = 'русский язык'
  languageCode = 'ru-RU'
  weight = 19

[languages.sl]
  contentDir = 'content.sl'
  languageName = 'Slovenščina'
  languageCode = 'sl-SI'
  weight = 20

[languages.hr]
  contentDir = 'content.hr'
  languageName = 'Hrvatski'
  languageCode = 'hr-HR'
  weight = 21

[languages.sr]
  contentDir = 'content.sr'
  languageName = 'Srpski'
  languageCode = 'sr-SP'
  weight = 22

[languages.bg]
  contentDir = 'content.bg'
  languageName = 'български език'
  languageCode = 'bg-BG'
  weight = 23

[languages.el]
  contentDir = 'content.el'
  languageName = 'Ελληνικά'
  languageCode = 'el-GR'
  weight = 24

[languages.tr]
  contentDir = 'content.tr'
  languageName = 'Türkçe'
  languageCode = 'tr-TR'
  weight = 25


[menu]
# [[menu.before]]
# [[menu.after]]
#  name = "r/HardFlaccidGroup"
#  url = "https://www.reddit.com/r/HardFlaccidGroup/"
#  weight = 10

# [[menu.after]]
#  name = "r/hardflaccidresearch"
#  url = "https://www.reddit.com/r/hardflaccidresearch/"
#  weight = 20

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true

  # (Optional, default favicon.png) Set the path to a favicon file.
  # If the favicon is /static/favicon.png then the path would be favicon.png
  # BookFavicon = 'favicon.png'

  # (Optional, default none) Set the path to a logo for the book.
  # If the logo is /static/logo.png then the path would be logo.png
  # BookLogo = 'logo.png'

  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = 'docs'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/alex-shpak/hugo-book'

  # (Optional, default 'commit') Specifies commit portion of the link to the page's last modified
  # commit hash for 'doc' page type.
  # Requires 'BookRepo' param.
  # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
  # Github uses 'commit', Bitbucket uses 'commits'
  # BookCommitPath = 'commit'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Edit path must point to root directory of repo.
  # BookEditPath = 'edit/main/exampleSite'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  # BookDateFormat = 'January 2, 2006'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = true

  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  # BookComments = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
  BookServiceWorker = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  BookTranslatedOnly = false